name: teste_dataset_mma

on:
  workflow_dispatch:
    inputs:
      organization:
        description: 'Qual deles vc quer destruir?'
        required: true
        type: choice
        options:
          - UFC Stats
          - Bellator Stats
          - PFL Stats
          - Rizin Stats
          - Aca Stats
          - Ksw Stats
          - Oktagon Stats
          - Cage Warrios Stats
          - LFA Stats
          - Jungle Fight Stats

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14.4'
      - run: pip install -r "${{ inputs.organization }}/requirements.txt"
      - env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          cd "${{ inputs.organization }}"
          python run_pipeline.py
